### PR TITLE
Fix and major update

### LINKED ISSUE #4: Crash on stock Kinetic install
Not quite sure what is going, or how to use this plugin at all, but when I try to run it, it just crashes after a couple of seconds (the GUI does show up first). Maybe the plugin has undocumented expectations that are not valid in my environment?

```
$ rosrun rqt_nav_view rqt_nav_view 
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_nav_view/nav_view.py", line 456, in _update
    self._mirror(self._map_item)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_nav_view/nav_view.py", line 491, in _mirror
    item.scale(-1, 1)
TypeError: QGraphicsItem.scale(): too many arguments
```

### LINKED ISSUE #5: rqt_nav_view ignores the origin of the map metadata
`msg.info.origin` should be used in map_cb to properly position the map. As it currently stands, if this value is non-zero (as is generally the case when using gmapping), the paths will not be placed in the correct locations.

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
- The plugin was not compatible with Qt 4.6 or newer. This is fixed now.
- Fixed the position and orientation of the goal and pose msg.
- Be compatible with map with moved origin.
- The map is rotated so that positive x is to the right, positive y to the top.
- Line to represent latest goal/pose is not deleted directly anymore.
- General cleanup

Update:
- Don't update map if the same
- Make configurable
- Fix save and restoring settings

Fixes #4, Fixes #5

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
@dirk-thomas everything should be working again

I have tested it on Melodic.

**Comment by MatthijsBurgh** [comment]
@dirk-thomas this PR got a bit big. As the current version is broken, I think this should be merged in some way. Do you prefer to keep it one PR, or would you like me to split it or any other preferences?

**Comment by dirk-thomas** [comment]
@MatthijsBurgh sorry but I am not a maintainer of this repo.

**Comment by MatthijsBurgh** [comment]
@dirk-thomas I taught you were, sorry for that.

@ablasdel am I correct you are the maintainer of this package?

**Comment by MatthijsBurgh** [comment]
@dirk-thomas could you please tell me who the maintainer of this package is? I put a lot of effort into this and I like it to be merged and released so that other people can enjoy this rqt plugin again.

**Comment by ablasdel** [comment]
@MatthijsBurgh I am the maintainer of the package and the correct person to be having this discussion with.
Thanks you for putting all this work in and sorry for the delay but I don't have a lot of time to spend on ROS 1 rqt_nav_view maintainer-ship nowadays.

You mentioned you tested on melodic, are you able to test on noetic?

**Comment by MatthijsBurgh** [comment]
@ablasdel Yes, I am able to test on Noetic. I will do that sometime in the upcoming week.

**Comment by MatthijsBurgh** [comment]
@ablasdel I catched some small improvements and tested the new version on both Melodic and Noetic. Both work as expected.

**Comment by MatthijsBurgh** [comment]
@ablasdel friendly ping ;)

**Review by ablasdel — APPROVED** [review]
Finally got a chance to review. Really nicely formed code. Big improvement.

When I went to test this myself I realized I didn't have an Ubuntu machine w/ a monitor to do so... 

So... Would you like to take over as maintainer for this ROS package?

**Comment by ablasdel** [comment]
@MatthijsBurgh might be a bit longer before I get some time to bloom this unfortunately. If you would like to take over as maintainer let me know and we can discuss.

**Comment by MatthijsBurgh** [comment]
@ablasdel Thank you for your invitation. Though I am already involved in other ROS packages. Which already require enough time. So I have to decline this one.

**Pull request merged**
